# Generated by Django 5.1.2 on 2024-10-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiesta',
            old_name='antiguedad',
            new_name='Construido',
        ),
    ]
