# Generated by Django 5.1.2 on 2024-10-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_antiguedad_fiesta_construido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiesta',
            old_name='Construido',
            new_name='construido',
        ),
    ]
